config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: %i[new create index show]
  get "flights/index"

  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights,
           class_name: "Flight",
           foreign_key: "departure_airport_id",
           inverse_of: :airport,
           dependent: :destroy
  has_many :arriving_flights,
           class_name: "Flight",
           foreign_key: "arrival_airport_id",
           inverse_of: :airport,
           dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight

  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings, dependent: :destroy

  scope :filter_by_date, ->(date) { where("DATE(departure_time) = ?", date) }

  def self.arriving_at(airport_code)
    joins(:arrival_airport)
      .where("arrival_airport.airport_code" => airport_code)
  end

  def self.departing_from(airport_code)
    joins(:departure_airport)
      .where("departure_airport.airport_code" => airport_code)
  end

  def self.list_formatted_departure_dates
    order(:departure_time).map(&:departure_date_formatted).uniq
  end

  def self.search(params)
    return none if params[:departure_date].blank?

    departing_from(params[:departure_airport])
      .arriving_at(params[:arrival_airport])
      .filter_by_date(params[:departure_date])
  end

  def departure_date_formatted
    departure_time.strftime("%m/%d/%Y")
  end

  def departure_time_formatted
    departure_time.strftime("%l:%M%P")
  end

  def format_duration
    minutes = flight_duration
    format(
      "%<hour>d:%<min>2.2d",
      {
        hour: minutes / 60,
        min: minutes % 60
      }
    )
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @passenger = Passenger.find_by email: params[:passenger_email]
  end

  def new
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new
    params[:booking][:passenger_number].to_i.times do
      @booking.passengers.build
    end
  end

  def create
    @booking = Booking.create(booking_params)

    if @booking.save
      if Rails.env.development?
        @booking.passengers.each do |passenger|
          PassengerMailer.with(passenger: passenger).confirmation_email.deliver_now!
        end
      end

      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end

    # respond_to do |format|
    #   if @booking.save
    #     if Rails.environment.development?
    #       @booking.passengers.each do |passenger|
    #         PassengerMailer.with(passenger: passenger).confirmation_email.deliver_now!
    #       end
    #     end
    #
    #     # format.html { redirect_to booking_path(@booking) }
    #     redirect_to booking_path(@booking)
    #   else
    #     render :new, status: :unprocessable_entity
    #   end
    # end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(
      :flight_id,
      passengers_attributes: %i[id first_name last_name email]
    )
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_codes = Airport.all.map(&:airport_code)
    @flight_dates = Flight.list_formatted_departure_dates
    @passengers = params.dig(:search, :passengers)

    @flights = Flight.search(search_params)
  end

  private

  def search_params
    return {} unless params.key?(:search)

    params[:search].slice(
      :departure_airport,
      :arrival_airport,
      :departure_date
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(name)
    file_path = Rails.root.join("app/assets/images/#{name}.svg")
    return File.read(file_path).html_safe if File.exist?(file_path)

    "(not found)"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flight_info_table.html.erb
<table class="border border-black mb-4 flex overflow-hidden sm:table">
  <thead class="flex flex-shrink-0 sm:table-header-group">
    <tr>
      <th scope="col" class="p-2 border border-black text-sky-800 block
                            sm:table-cell">Departs From</th>
      <th scope="col" class="p-2 border border-black text-sky-800 block
                            sm:table-cell">Arrives At</th>
      <th scope="col" class="p-2 border border-black text-sky-800 block
                            sm:table-cell">Departure Date</th>
      <th scope="col" class="p-2 border border-black text-sky-800 block
                            sm:table-cell">Departure Time</th>
      <th scope="col" class="p-2 border border-black text-sky-800 block
                            sm:table-cell">Flight Duration</th>
    </tr>
  </thead>
  <tbody class="flex sm:table-row-group">
    <tr class="text-center flex flex-col sm:table-row">
      <td class="border border-black block p-2 sm:table-cell sm:p-1">
        <%= flight.departure_airport.airport_code %>
      </td>
      <td class="border border-black block p-2 sm:table-cell sm:p-1">
        <%= flight.arrival_airport.airport_code %>
      </td>
      <td class="border border-black block p-2 sm:table-cell sm:p-1">
        <%= flight.departure_date_formatted %>
      </td>
      <td class="border border-black block p-2 sm:table-cell sm:p-1">
        <%= flight.departure_time_formatted %>
      </td>
      <td class="border border-black block p-2 sm:table-cell sm:p-1">
        <%= flight.format_duration %>
      </td>
    </tr>
  </tbody>
</table>

app/views/bookings/_form.html.erb
<%= form_with model: booking,
  html: { class: "flex flex-col items-center lg:w-[40%]" } do |form| %>
  <%= form.hidden_field :flight_id, value: flight.id %>
  <div class="flex md:flex-row flex-col md:flex-wrap gap-4 justify-center">
    <%= form.fields_for :passengers do |sub_form| %>
      <div class="flex flex-col gap-2">
        <h3 class="font-bold text-center">
          <%= "#{(sub_form.index + 1).ordinalize} Passenger" %>
        </h3>
        <div class="flex flex-col">
          <%= sub_form.label :first_name,
            class: "text-sky-800 uppercase tracking-wider text-sm"
          %>
        <%= sub_form.text_field :first_name,
          required: true,
          class: "border-2 border-black p-1"
        %>
        </div>
        <div class="flex flex-col">
          <%= sub_form.label :last_name,
            class: "text-sky-800 uppercase tracking-wider text-sm"
          %>
        <%= sub_form.text_field :last_name,
          required: true,
          class: "border-2 border-black p-1"
        %>
        </div>
        <div class="flex flex-col mb-4">
          <%= sub_form.label :email,
            class: "text-sky-800 uppercase tracking-wider text-sm"
          %>
          <%= sub_form.email_field :email,
            required: true,
            class: "border-2 border-black p-1"
          %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Book This Flight", class: "btn-primary mb-10 mt-2" %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">Enter a passenger email to find Booking</h1>

<%= form_with url: bookings_path, method: :get do |form| %>
  <div class="mb-10 flex gap-4 flex-col md:flex-row">
    <%= form.label "Email", class: "hidden" %>
    <%= form.email_field "passenger_email",
      placeholder: "example@email.com",
      class: "border border-black p-2 rounded-md"
    %>
    <%= form.submit "Search", class: "btn-primary" %>
  </div>
<% end %>

<% if @passenger.present? %>
  <h2 class="font-bold text-xl mb-2 text-amber-700">
    Hello <%= @passenger.first_name %>!
  </h2>
  <p class="font-bold mb-1">You are booked for the following flight:</p>
  <%= render "flight_info_table", flight: @passenger.booking.flight %>
<% elsif request.query_string.present? %>
  <p class="text-red-700 font-bold">
    - No bookings were found for this email -
  </p>
<% end %>

app/views/bookings/new.html.erb
<h1 class="text-3xl mb-4 mt-4 font-bold text-sky-600">Book Your Flight</h1>

<% if @booking.errors.any? %>
  <div class="error">
    <h2 class="text-xl mb-2 font-bold text-red-700">
      Error(s) prohibited this flight from being booked.
    </h2>
  </div>
  <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <li class="text-center"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<% if @flight.present? %>
  <h2 class="text-xl mb-2 font-bold">Flight Information</h2>
  <%= render "flight_info_table", flight: @flight %>
  <%= render "form", booking: @booking, flight: @flight %>
<% end %>

app/views/bookings/show.html.erb
<h1 class="text-3xl mb-4 mt-4 font-bold text-sky-600">Booking</h1>

<h2 class="text-xl mb-2 font-bold">Flight Info</h2>
<%= render "flight_info_table", flight: @booking.flight %>

<div>
  <% @booking.passengers.each_with_index do |passenger, idx| %>
    <h3 class="font-bold"><%= (idx + 1).ordinalize %> Passenger</h3>
    <ul class="mb-2">
      <%= passenger.first_name %>
      <%= passenger.last_name %>
    </ul>
  <% end %>
</div>

app/views/flights/_search_form.html.erb
<%= form_with scope: :search, url: root_path, method: :get, html: { class: styles } do |form| %>
  <div class="mb-6 flex gap-1 flex-col md:flex-row">
    <%= form.label :departure_airport, class: "hidden" %>
    <%= form.select :departure_airport,
      airport_codes,
      { prompt: "Select departure airport" },
      { class: "p-2 border border-transparent focus:border-black" }
    %>

    <%= form.label :arrival_airport, class: "hidden" %>
    <%= form.select :arrival_airport,
      airport_codes,
      { prompt: "Select destination" },
      { class: "p-2 border border-transparent focus:border-black" }
    %>

    <%= form.label :departure_date, class: "hidden" %>
    <%= select :search,
      :departure_date,
      flight_dates,
      { prompt: "Select Date" },
      { class: "p-2 border border-transparent focus: border-black" }
    %>

    <%= form.label :passengers, "Number of passengers:", class: "hidden" %>
    <%= form.select :passengers,
      (1..4).map { [ "#{_1} passengers", _1 ]},
      { prompt: "Number of passengers" },
      { class: "p-2 border border-transparent focus:border-black" }
    %>
  </div>

  <div class="flex justify-center">
    <%= form.submit "Search", class: "btn-primary" %>
  </div>
<% end %>

app/views/flights/_select_form.html.erb
<h2 class="text-xl font-bold mb-4">Matching Flights:</h2>

<%= form_with url: new_booking_path,
  method: :get,
  html: { id: "flight_form" } do |form|
%>
<% end %>

<table class="border border-black mb-4">
  <thead>
    <tr>
      <th scope="col" class="p-2 border border-black text-sky-800">Select Flight</th>
      <th scope="col" class="p-2 border border-black text-sky-800">Departs From</th>
      <th scope="col" class="p-2 border border-black text-sky-800">Arrives At</th>
      <th scope="col" class="p-2 border border-black text-sky-800">Flight Duration</th>
    </tr>
  </thead>
  <tbody>
    <% flights.each do |flight| %>
      <tr class="text-center">
        <td class="border border-black">
          <%= radio_button("booking", "flight_id", "#{flight.id}", form: "flight_form") %>
          <%= hidden_field(:booking,
           :passenger_number,
           value: passengers,
           form: "flight_form")
         %>
        </td>
        <td class="border border-black"><%= flight.departure_airport.airport_code %></td>
        <td class="border border-black"><%= flight.arrival_airport.airport_code %></td>
        <td class="border border-black"><%= flight.format_duration %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= submit_tag "Book this flight",
    form: "flight_form",
    class: "btn-primary"
  %>
</div>

app/views/flights/index.html.erb
<h1 class="text-3xl mb-4 mt-4 font-bold">Search Flights</h1>

<%= render "search_form",
  airport_codes: @airport_codes,
  flight_dates: @flight_dates,
  styles: "mb-8"
%>

<% if @flights.exists? %>
  <%= render "select_form", flights: @flights, passengers: @passengers %>
<% elsif request.query_string.present? %>
  <p class="text-red-700 font-bold">
  - No flights match the given criteria -
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="flex flex-col min-h-screen">
    <header class="bg-sky-600 border-b-2 border-sky-800 mb-4">
      <nav class="flex items-center divide-x-2 divide-sky-800">
        <span class="text-white mx-4">
          <%= svg "airplane-takeoff" %>
        </span>
        <%= link_to "Search Flights",
                    root_path,
                    class: "text-white text-2xl p-4 hover:bg-sky-800
                            transition-all duration-200
                            after:block after:w-0 after:h-0.5 after:bg-white
                            after:transition-all hover:after:w-full" %>
        <%= link_to "Find Booking",
                    bookings_path,
                    class: "text-white text-2xl p-4 hover:bg-sky-800
                            transition-all duration-200
                            after:block after:w-0 after:h-0.5 after:bg-white
                            after:transition-all hover:after:w-full" %>
      </nav>
    </header>

    <main class="flex flex-1 flex-col items-center">
      <%= yield %>
    </main>

    <footer class="bg-sky-600 border-t-2 border-sky-800 flex justify-center gap-4">
      <%= link_to svg("github") + "Github",
                  "https://www.github.com/JoshDevHub/Flight-Booker",
                  target: "_blank",
                  class: "text-white text-2xl hover:bg-sky-800 p-2 flex items-center gap-2" %>
    </footer>
  </body>
</html>